kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
    reloader.stakater.com/auto: "true"
  name: example
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-openshift
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hello-openshift
    spec:
      containers:
        - name: rollouts-test-app
          image: >-
            {{ .Values.rollouts_test_app_image.repository }}/{{
            .Values.rollouts_test_app_image.image }}:{{
            .Values.rollouts_test_app_image.tag }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          envFrom:
            - configMapRef:
                name: rollouts-configmap
