apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollouts-test
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rollouts-test
  template:
    metadata:
      labels:
        app: rollouts-test
    spec:
      containers:
      - name: rollouts-test-app
        image: "{{ .Values.rollouts_test_app_image.repository }}/{{ .Values.rollouts_test_app_image.image }}:{{ .Values.rollouts_test_app_image.tag }}"
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        envFrom:
        - configMapRef:
            name: rollouts-configmap
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause: {duration: 1m}
      - setWeight: 40
      - pause: {duration: 1m}
      - setWeight: 60
      - pause: {duration: 1m}
      - setWeight: 80
      - pause: {duration: 1m}
